# Generated by Django 4.1.7 on 2023-05-01 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='URL')),
            ],
            options={
                'ordering': ('id',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('old', models.CharField(default='Для взрослых собак', max_length=25)),
                ('ingredients', models.CharField(max_length=255)),
                ('breed', models.CharField(default='Для всех пород', max_length=25)),
                ('weight', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrumshop.category')),
            ],
            options={
                'ordering': ('id',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
